/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define APP_DISPLAY_NAME "Test App"

#define APP_ID "org.robertomorrison.test_app"

#define APP_NAME "test_app"

#define DATA_DIR "share"

#define DEFAULT_RESOURCE_PATH "/org/robertomorrison/test_app"

#define DEVELOPER "robertomorrison"

#define DEVELOPER_NAME "Roberto Morrison"

#define GETTEXT_PACKAGE "org.robertomorrison.test_app"

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE_ICON_NAME "org.robertomorrison.test_app"

#define PACKAGE_VERSION "0.1.1.alpha"

#define WEBSITE "https://github.com/robertomorrison0/test_app"

